### ISSUE TITLE
Доработки к РК#1

### ISSUE THREAD

**Issue by marinatells** [frontend-park-mail-ru/2018_1_perpetuum_mobile#5]
- [x] избавиться от форм в пагинации
- [x] валидация загрузки изображений 
- [x] кастомные ошибки в полях форм
- [x] единый код стайл (отсутствие зоопарка использования всего и вся)
- [x] валидация инпута во время ввода

**Comment by diarmind** [comment]
Марина, посмотрите ветку refactoring, сейчас Саша ревьюит пул с неё. Исправили ваши замечания.
